FROM alpine:3.7 

MAINTAINER Ricardson Williams <ricardsonwilliams@gmail.com>

RUN \
	apk --no-cache add \
	caddy

VOLUME /srv
WORKDIR /srv

ADD Caddyfile /etc/Caddyfile

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["/usr/sbin/caddy"]
CMD ["--conf", "/etc/Caddyfile"]
