version: '2'

services:
  docker-laravel:
    build:
      context: .
    image: laravel 
    ports:
      - "80:8000"
    #volumes:
    #  - /srv/docker/apache:/var/www/localhost/htdocs
  db:
    image: mariadb
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: teste 
